# Generated by Django 5.0.4 on 2024-04-19 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("collection_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("collCover", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("typ", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("year", models.IntegerField()),
                ("pieceCover", models.CharField(max_length=1000)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="genre.collection",
                    ),
                ),
            ],
        ),
    ]
